# Generated by Django 2.2.3 on 2019-12-31 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propertytype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(blank=True, help_text='optional', null=True, upload_to='uploads/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'property',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=50)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bath', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sqrt', models.CharField(blank=True, max_length=20, null=True)),
                ('sale_type', models.CharField(blank=True, choices=[('rent', 'RENT'), ('sale', 'SALE'), ('sale & rent', 'SALE & RENT')], max_length=20, null=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('image1', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('image4', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='estate_app.Propertytype')),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
                'ordering': ['-date_updated'],
            },
        ),
    ]
