# Generated by Django 2.2.3 on 2019-12-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0002_auto_20191231_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='propertytype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
