# Generated by Django 2.2.3 on 2019-12-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0004_property_image5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(help_text='description aboot this person')),
                ('facebook_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('twitter_url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
