# Generated by Django 2.2.3 on 2019-12-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0005_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
