# Generated by Django 2.2.3 on 2019-12-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0006_agent_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='about',
        ),
        migrations.AddField(
            model_name='agent',
            name='position',
            field=models.CharField(blank=True, help_text='description aboot this person', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
