# Generated by Django 2.2.3 on 2020-01-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0009_agent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('rent', 'RENT'), ('sale', 'SALE'), ('sale or rent', 'SALE or RENT')], max_length=20, null=True),
        ),
    ]
