# Generated by Django 2.2.3 on 2020-01-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0010_auto_20200102_0306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-date_updated'], 'verbose_name': 'Leader', 'verbose_name_plural': 'Leaders'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, help_text='eg single room,story building', max_length=200, null=True),
        ),
    ]
