# Generated by Django 2.2.3 on 2020-01-27 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('estate_app', '0016_gallary'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallary',
            name='name',
            field=models.TextField(blank=True, help_text='enter something about this image', null=True, verbose_name='about'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phonenumber',
            field=models.TextField(max_length=15),
        ),
    ]
