# Generated by Django 2.2.3 on 2020-01-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0017_auto_20200127_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phonenumber',
            field=models.CharField(max_length=15),
        ),
    ]
