# Generated by Django 2.2.3 on 2020-01-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0018_auto_20200127_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
