# Generated by Django 2.2.3 on 2020-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0019_auto_20200127_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
