# Generated by Django 2.2.3 on 2020-01-28 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_app', '0026_auto_20200128_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='user_phone',
        ),
        migrations.AlterField(
            model_name='property',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estate_app.Phone'),
        ),
    ]
